### ISSUE TITLE
Modal change URL in NuxtJS

### ISSUE THREAD

**Issue by tagmetag** [yTakkar/Vue-Mini-Social-Network#2]
I've created a Social Network project like you did by NuxtJS.
The problem I want to said about:
If you go to Twitter's website, and open a tweet from any place (your own timeline, someone else's timeline, a list ...), three things happen:

1. A modal with the tweet opens
2. the URL changes to an absolute URL pointing to that tweet
3. Something doesn't change, though: the background of the modal. Even though we started from e.g. twitter.com/linus_borg and went to twitter.com/vuejs/status/xxxxx when we opened the modal, my profile's timeline is still in the brackground.

What package did you use for your project. Is it work with Nuxtjs?
Thank you!

**Comment by yTakkar** [comment]
It is not working with NuxtJS
