### ISSUE TITLE
Login/register not possible

### ISSUE THREAD

**Issue by prodigy7** [yTakkar/Vue-Mini-Social-Network#4]
I can't get working that SPA, error when I try to register:
```
(node:18965) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ER_NO_DEFAULT_FOR_FIELD: Field 'bio' doesn't have a default value
(node:18965) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I would also use existing users, but passwords for users are not documented (password are encrypted in database)

**Comment by yTakkar** [comment]
You could get it working, go to `phpmyadmin` and update `bio` column of `users` with a default value of `''`.
Dummy user:
takkar, password: takkar.
But many got it working without setting a default value for `bio`.
